data:
  data_path: /Users/ksc/Desktop/Нейротемка/code_local/Уточнение психофизиологических состояний 2023/3_Усталость и сильная усталость/data
  cache_processed_path: /Users/ksc/Desktop/Нейротемка/code_local/Уточнение психофизиологических состояний 2023/3_Усталость и сильная усталость/cache
  chunk_length: 250
  chunk_stride: 225
  num_chunks: 256
  batch_size: 4
  num_workers: 2
  persistent_workers: true
  limit: null
  pin_window: true
encoder:
  # inp_size: 1000 # 4 * 500
  emb_dim: 512
context_network: 
  emb_dim: 512
  ffn_dim: 3072
  nhead: 8
  transformer_num_layers: 3
  mask_prob: 0.065
  mask_length: -1
  min_masked: 128
  temp: 0.1
  num_negatives: 80
optimizer:
  lr: 10.0e-4
  weight_decay: 0 # 1.0e-2
scheduler:
  part_warmup_steps: 0.05
training:
  num_epochs: 1500
  heavy_logs_every: 10
save: 
  dir: /Users/ksc/Desktop/Нейротемка/code_local/neural_foundation/src/checkpoints
  every: 350