data:
  data_path: /home/ps5359/data/exp_3/h5
  cache_processed_path: /home/ps5359/data/exp_3/cache
  train_length: 73800 # just less than 5min, produces 768 chunks
  dataset_mode: "full"
  rebuild_cache: false
  limit: null
  batch_size: 32
  persistent_workers: true
encoder:
  # inp_size: 1000 # 4 * 500
  emb_dim: 512
  norm: 'group'
context_network: 
  emb_dim: 512
  ffn_dim: 2048
  nhead: 8
  transformer_num_layers: 3
  mask_prob: 0.065
  mask_length: 10
  min_masked: 384
  temp: 0.1
  num_negatives: 80
  pe:
    type: 'sin'
    max_len: 1000
optimizer:
  lr: 3.0e-4
  weight_decay: 0 # 1.0e-2
scheduler:
  part_warmup_steps: 0.05
training:
  device: "cuda"
  num_epochs: 200
  heavy_logs_every: 30
save: 
  dir: /home/ps5359/checkpoints
  every: 25