data:
  data_path: /home/ubuntu/small_data/small_data
  limit: 64
  chunk_length: 500
  chunk_stride: 450
  num_chunks: 256
  batch_size: 64
  num_workers: 4
  pin_window: false
  buffer_length: 500 # 250 is enough, but to be sure
  clip_val: 2
encoder:
  inp_size: 2000 # 4 * 500
  emb_dim: 768
context_network: 
  emb_dim: 768
  ffn_dim: 3072
  nhead: 8
  transformer_num_layers: 6
  mask_prob: 0.5
  mask_length: 1
  log_temp: 0 # e ^ 1.1 = 3.004
optimizer:
  lr: 1.0e-4
  weight_decay: 1.0e-1
scheduler:
  warmup_steps: 30
  total_steps: 300
training:
  num_epochs: 300
  heavy_logs_every: 50