data:
  data_path: /home/ubuntu/small_data/sloped_brickwall
  is_processed: true
  limit: 500
  chunk_length: 250
  chunk_stride: 225
  num_chunks: 64
  batch_size: 64
  num_workers: 0
  pin_window: true
  last_is_serial: true
encoder:
  inp_size: 1000 # 4 * 500
  emb_dim: 768
context_network: 
  emb_dim: 768
  ffn_dim: 3072
  nhead: 8
  transformer_num_layers: 12
  mask_prob: 0.5
  mask_length: 1
  log_temp: 0 # e ^ 1.1 = 3.004
optimizer:
  lr: 3.0e-4
  weight_decay: 1.0e-2
scheduler:
  warmup_steps: 300
  total_steps: 30000
training:
  num_epochs: 30000
  heavy_logs_every: 30
save: 
  dir: /home/ubuntu/neural_foundation/src/checkpoints
  every: 250