data:
  data_path: /Users/ksc/Desktop/Нейротемка/code_local/Уточнение психофизиологических состояний 2023/3_Усталость и сильная усталость/data
  cache_processed_path: /Users/ksc/Desktop/Нейротемка/code_local/Уточнение психофизиологических состояний 2023/3_Усталость и сильная усталость/cache
  train_length: 73800 # just less than 5min, produces 768 chunks
  dataset_mode: "full"
  rebuild_cache: false
  limit: 200
  batch_size: 2
  num_workers: 2
  persistent_workers: true
encoder:
  # inp_size: 1000 # 4 * 500
  emb_dim: 512
  norm: 'group'
context_network: 
  emb_dim: 512
  ffn_dim: 2048
  nhead: 8
  transformer_num_layers: 3
  mask_prob: 0.065
  mask_length: 10
  min_masked: 384
  temp: 0.1
  num_negatives: 80
  pe:
    # type: 'conv'
    # kernel_size: 127
    # groups: 16
    # type: "learned"
    # max_len: 1000
    type: 'sin'
    max_len: 1000
optimizer:
  lr: 3.0e-4
  weight_decay: 0 # 1.0e-2
scheduler:
  part_warmup_steps: 0.05
training:
  device: "mps"
  num_epochs: 10
  heavy_logs_every: 10
save: 
  dir: /Users/ksc/Desktop/Нейротемка/code_local/neural_foundation/src/checkpoints
  every: 25