data_train:
  data_path: /root/neural_data/1k/h5
  cache_processed_path: /root/neural_data/1k/cache
  train_length: 73728 
  dataset_mode: "full"
  batch_size: 128
  rebuild_cache: false
  limit: null
  target_config: 
    user_id: False
    activity: False
  clipped_threshold: 0.3 
data_val:
  data_path: /root/neural_data/full_clean/h5
  cache_processed_path: /root/neural_data/full_clean/cache/
  train_length: 73728 
  dataset_mode: "full"
  batch_size: 128
  rebuild_cache: false
  limit: null
  target_config: 
    user_id: True
    activity: False
  clipped_threshold: 100
encoder:
  # inp_size: 1000 # 4 * 500
  emb_dim: 512
  norm: 'group'
context_network: 
  emb_dim: 512
  ffn_dim: 2048
  nhead: 8
  transformer_num_layers: 6
  mask_prob: 0.065
  mask_length: 10
  min_masked: 384
  temp: 0.1
  num_negatives: 80
  pe:
    type: 'sin'
    max_len: 1000
optimizer:
  lr: 1.2e-3
  weight_decay: 0
scheduler:
  part_warmup_steps: 0.05
training:
  device: "cuda"
  num_epochs: 200
  heavy_logs_every: -1
save: 
  dir: /root/checkpoints
  every: -1