data_train:
  data_path: /home/ps5359/data/1k/h5
  cache_processed_path: /vast/ps5359/test_cache_1k/cache/
  train_length: 73728 
  dataset_mode: "full"
  batch_size: 64
  rebuild_cache: false
  limit: 3200
  target_config: 
    user_id: False
    activity: False
  clipped_threshold: 0.3 
encoder:
  # inp_size: 1000 # 4 * 500
  emb_dim: 512
  norm: 'group'
context_network: 
  emb_dim: 512
  ffn_dim: 2048
  nhead: 8
  transformer_num_layers: 3
  mask_prob: 0.065
  mask_length: 10
  min_masked: 384
  temp: 0.1
  num_negatives: 80
  pe:
    type: 'sin'
    max_len: 1000
optimizer:
  lr: 3.0e-4
  weight_decay: 0
scheduler:
  part_warmup_steps: 0.05
training:
  device: "cuda"
  num_epochs: 3